### PR TITLE
Local reducer tables

### PR DESCRIPTION
**Pull request by neboat**
This PR contains changes to the OpenCilk compiler to support a new implementation of reducers in the runtime system using only local reducer tables.

### CODE REVIEW

**Comment by VoxSciurorum** [comment]
Calling `__hyper_lookup` with bad arguments crashes the compiler.  A fix is in branch jfc/local at 3437495bc28513c39876555aa4ba4ecdb593df04.

**Comment by neboat** [comment]
@VoxSciurorum I tried the `jfc/local` branch, and I'm getting a compiler crash when building Cilkscale.  The crash seems to complain that the `identity` function for the `ostream` reducer has the wrong type.

**Comment by VoxSciurorum** [comment]
I fixed the crash.  See 86f1475fe91b418856b64fc60890870ea30cdbbd.  The cilkscale code was either not compiled on FreeBSD or was compiled with different options.

**Comment by VoxSciurorum** [comment]
The features in this pull request have already made their way into the compiler.

**Pull request closed without merging**
